package hostset

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

// Round trip first, because the file is GENERATED by the picker and hand-edited by
// the user, and a generated file that cannot read its own output is a file that
// drifts from the thing that writes it.
func TestHostsRoundTrip(t *testing.T) {
	path := filepath.Join(t.TempDir(), "hosts.toml")
	want := []Entry{
		{Alias: "nuc", Enabled: true, Tags: []string{"work", "eu"}},
		{Alias: "web-app", Enabled: true, Tags: []string{"prod"}, TmuxArgs: []string{"-L", "deploy"}},
		{Alias: "eu", Enabled: false},
	}
	if err := SaveHosts(path, want); err != nil {
		t.Fatal(err)
	}
	got, err := LoadHosts(path)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("round trip changed the set:\n got %+v\nwant %+v", got, want)
	}
}

// An absent file is "nothing decided yet", which is what makes the picker open
// itself on a first run — not an error the user has to clear first.
func TestLoadHostsTreatsAnAbsentFileAsNoDecisions(t *testing.T) {
	got, err := LoadHosts(filepath.Join(t.TempDir(), "nope.toml"))
	if err != nil {
		t.Fatalf("an absent file must not be an error: %v", err)
	}
	if len(got) != 0 {
		t.Fatalf("got %+v, want none", got)
	}
}

// Malformed content is a warning, not a wipe. The same rule the hidden set follows
// (§18): a file the user edited badly must not silently discard their decisions.
func TestLoadHostsRefusesToGuessAtBrokenContent(t *testing.T) {
	path := filepath.Join(t.TempDir(), "hosts.toml")
	os.WriteFile(path, []byte("this is not toml at all ]]]"), 0o600)
	if _, err := LoadHosts(path); err == nil {
		t.Error("broken content must be reported, so the picker can say so instead of " +
			"writing a fresh file over it")
	}
}

// The host list is CONFIG, and this is the assertion the drift got past.
//
// `DefaultPath` resolved through `statedir` for a whole branch, i.e.
// $XDG_STATE_HOME/tmux-hub/hosts.toml, while README.md and docs/design.md §9 both
// documented ~/.config/tmux-hub/hosts.toml. Following the documentation therefore
// produced a file nothing read — and it could not complain, because an absent host
// list is a legitimate empty fleet (§16's zero configuration), so the failure had no
// symptom at all.
//
// Both directions are asserted, and the second one is the discriminator: an equality
// test alone stays green if someone points configdir at XDG_STATE_HOME, since both
// helpers join `tmux-hub` onto a base and would then agree.
func TestDefaultPathIsConfigAndNotState(t *testing.T) {
	t.Setenv("XDG_CONFIG_HOME", "/xdg/config")
	t.Setenv("XDG_STATE_HOME", "/xdg/state")

	if got, want := DefaultPath(), "/xdg/config/tmux-hub/hosts.toml"; got != want {
		t.Errorf("DefaultPath = %q, want %q — the README and §9 both document the config "+
			"directory, and a file written where nothing reads it is silent", got, want)
	}
	if strings.HasPrefix(DefaultPath(), "/xdg/state") {
		t.Errorf("DefaultPath = %q is under the STATE directory: hosts.toml holds the "+
			"user's decisions and is hand-editable, while state holds what the hub derived "+
			"for itself (hidden.json, history.jsonl)", DefaultPath())
	}
}

// The default follows $XDG_CONFIG_HOME rather than hardcoding ~/.config, which is what
// makes the hub usable on a machine that relocates its config — and what lets every
// test above point it at a temp directory instead of the operator's real host list.
func TestDefaultPathHonoursXDGConfigHome(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", dir)
	if got, want := DefaultPath(), filepath.Join(dir, "tmux-hub", "hosts.toml"); got != want {
		t.Fatalf("DefaultPath = %q, want %q", got, want)
	}
}

// The reader and the writer must agree on WHERE, not just on the format. TestHostsRoundTrip
// above passes a path both ways, so it proves the two agree about bytes while saying
// nothing about location — which is exactly the half that broke: the picker generated a
// perfectly valid file, and the reader looked somewhere else.
//
// So this round trip names no path at all. Both sides ask DefaultPath, which is what the
// binary does through its one `-hosts` flag, and the file has to come back.
func TestSaveAndLoadAgreeOnDefaultPath(t *testing.T) {
	// Every input to the derivation is sandboxed, not just the one DefaultPath reads
	// today. This test WRITES through a path it does not spell, so if the derivation
	// ever changes source — which is exactly what this round of work did — an
	// un-sandboxed variable would put a real file in the operator's own config or state
	// directory. A test that writes through a derived path must own the whole derivation.
	t.Setenv("XDG_CONFIG_HOME", t.TempDir())
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	t.Setenv("HOME", t.TempDir())

	want := []Entry{{Alias: "nuc", Enabled: true, TmuxArgs: []string{"-L", "work"}}}
	if err := SaveHosts(DefaultPath(), want); err != nil {
		t.Fatalf("SaveHosts to the default path: %v", err)
	}
	got, err := LoadHosts(DefaultPath())
	if err != nil {
		t.Fatalf("LoadHosts from the default path: %v", err)
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("the writer and the reader disagree about the default location:\n got %+v\nwant %+v",
			got, want)
	}
	// And the file is really THERE, not merely round-tripping through some other path
	// both calls happen to share: an assertion on the bytes on disk cannot be satisfied
	// by two functions agreeing with each other.
	if _, err := os.Stat(DefaultPath()); err != nil {
		t.Errorf("nothing on disk at %s: %v", DefaultPath(), err)
	}
}

// The written file is meant to be read by a person, so the shape is asserted.
func TestSavedFileIsReadable(t *testing.T) {
	path := filepath.Join(t.TempDir(), "hosts.toml")
	SaveHosts(path, []Entry{{Alias: "nuc", Enabled: true, Tags: []string{"work"}}})
	b, _ := os.ReadFile(path)
	for _, want := range []string{"[[host]]", `alias = "nuc"`, "enabled = true", `tags = ["work"]`} {
		if !strings.Contains(string(b), want) {
			t.Errorf("the file does not contain %q:\n%s", want, b)
		}
	}
}
